os: linux
dist: focal
language: node_js
node_js: 14.15.1
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGPORT=5433
before_install:
  - sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - service postgresql restart
  - sleep 1
  - psql -c 'create database impactmarkettest;' -U postgres
install: yarn
script: yarn coverage:ci
