os: linux
dist: focal
language: node_js
node_js: 14.15.1
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGVER=12
  - PGPORT=5433
before_install:
  - psql -c 'create database impactmarkettest;'
install: yarn
script: yarn coverage:ci
