os: linux
dist: focal
language: node_js
node_js: 14.15.1
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGPORT=5433
before_install:
  - sudo -u postgres psql --command '\password postgres'
  - psql -c 'create database impactmarkettest;' -U postgres -p postgres
install: yarn
script: yarn coverage:ci
