os: linux
dist: focal
language: node_js
node_js: 14.15.1
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGVER=12
  - PGPORT=5433
before_install:
  - psql -c 'create database impactmarkettest;'
  - psql -c "CREATE USER citest WITH PASSWORD 'test101';"
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE impactmarkettest TO citest;"
  - sudo apt-get update
  - sudo apt-get install -y build-essential git python3 curl
install: yarn
script: yarn coverage:ci
