version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run: yarn
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: yarn coverage
      - store_artifacts:
          path: coverage

