version: 2.1

jobs:
  coverage:
    docker:
      - image: circleci/node:14.15.1
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: citest
          POSTGRES_DB: impactmarkettest
    steps:
      - checkout
      - run: yarn
      - run:
          name: "Run Tests and do Coverage Reports"
          command: yarn coverage:ci
          environment:
            DATABASE_URL: postgresql://citest@localhost/impactmarkettest
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  test:
    jobs:
      - coverage
